name: scrumpoker_flutter
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  asp: ^1.3.0
  asuka: ^2.2.0
  dson_adapter: ^1.2.0+2
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.1.0
  flutter_modular: ^6.0.4+1
  shared_preferences: ^2.2.0
  socket_io_client: ^2.0.3+1
  url_strategy: ^0.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
  - .env
